#!/bin/bash

if [ "$(whoami)" != "root" ]; then
    echo "Please run the script as root."
    exit 1
fi

interfaces=$(ifconfig | grep -o '^[^ ]*' | sed s/":"/""/g)

for interface in $interfaces; do
    ip=$(ifconfig $interface | awk '/inet /{print $2}')
    mac=$(ifconfig $interface | awk '/ether /{print $2}')
    echo -e "\e[1m$interface $ip $mac"
done
